/* Pulitzer Blitz Fitness — program + workout content
   Original content, phase-gated for postpartum safety. Not medical advice. */

const PHASES = [
  {
    id: "bliss",
    label: "Newborn Bliss",
    emoji: "🌸",
    weeks: [0, 2],
    tagline: "Breathe, rest, and reconnect. No core work yet — just you and baby.",
    unlockNote: null,
  },
  {
    id: "bloom",
    label: "Gentle Bloom",
    emoji: "🌷",
    weeks: [2, 6],
    tagline: "Gentle pelvic floor + core reconnection while you wait for clearance.",
    unlockNote: null,
  },
  {
    id: "sunshine",
    label: "Sunshine Strength",
    emoji: "☀️",
    weeks: [6, 12],
    tagline: "Low-impact strength & sculpt — once your provider says go.",
    unlockNote: "Ask your OB/midwife for clearance first (usually your 6-week visit, or 8–12 weeks after a C-section).",
  },
  {
    id: "fullbloom",
    label: "Full Bloom",
    emoji: "🌺",
    weeks: [12, 999],
    tagline: "Full sculpt, cardio & strength — build your glow back up.",
    unlockNote: "Ask your OB/midwife for clearance first (usually your 6-week visit, or 8–12 weeks after a C-section).",
  },
];

const CATEGORIES = [
  { id: "breathe", label: "Breathe & Connect", emoji: "🫧" },
  { id: "walk", label: "Sunshine Walks", emoji: "🌴" },
  { id: "pelvic", label: "Pelvic Floor", emoji: "🌼" },
  { id: "pilates", label: "Postnatal Pilates", emoji: "🩰" },
  { id: "sculpt", label: "Sculpt & Tone", emoji: "🍹" },
  { id: "cardio", label: "Dance Cardio", emoji: "🕺" },
  { id: "strength", label: "Strength", emoji: "🏋️‍♀️" },
  { id: "stretch", label: "Stretch & Restore", emoji: "🧘‍♀️" },
];

const AFFIRMATIONS = [
  "You grew a human. A little laundry pile can wait. 🌺",
  "Progress, not perfection, darling. ✨",
  "Strong mama, soft heart, great tan lines incoming. 🍊",
  "Ten minutes counts. You showed up. 💛",
  "Your body just did something incredible. Be gentle with it. 🐚",
  "Preppy on the outside, powerhouse on the inside. 🎀",
  "One rep, one breath, one bloom at a time. 🌷",
  "You're not behind — you're right on time for you. ☀️",
];

const WORKOUTS = [
  // ---------- Newborn Bliss (0-2 weeks) ----------
  {
    id: "breathe-101",
    title: "Belly Breathing 101",
    category: "breathe",
    phase: "bliss",
    duration: 5,
    equipment: "None — can do in bed",
    emoji: "🫧",
    summary: "Reconnect with your core & pelvic floor through breath, lying down.",
    steps: [
      { name: "360° Breathing", detail: "Lying on back, knees bent. Inhale through nose, let belly + ribs expand in all directions. Exhale slowly through mouth, gently drawing belly button toward spine. 10 breaths." },
      { name: "Pelvic Floor + Breath", detail: "As you exhale, gently lift pelvic floor (like stopping a stream of pee) without clenching glutes. Hold 2 sec, release fully on inhale. 8 reps." },
      { name: "Rest & Notice", detail: "Lie still for 1 minute. Notice any tension, heaviness, or pulling. No pain should be present." },
    ],
    safetyNote: "Stop if you feel dizzy, pain, or heavy bleeding increases. This is safe as early as day 1–2 if you feel up to it.",
  },
  {
    id: "gentle-stroll",
    title: "Gentle Nursery Stroll",
    category: "walk",
    phase: "bliss",
    duration: 10,
    equipment: "Stroller or baby carrier (optional)",
    emoji: "🌴",
    summary: "A short, slow walk around the block (or the living room!).",
    steps: [
      { name: "Warm-up", detail: "Stand tall, roll shoulders back 5x, gentle neck stretches side to side." },
      { name: "Stroll", detail: "Walk at an easy, chatting pace for 8 minutes. Stop anytime you feel tired." },
      { name: "Cool-down", detail: "Stand and take 5 deep belly breaths before sitting back down." },
    ],
    safetyNote: "Listen to your body — bleeding that increases or turns bright red is a sign to rest more.",
  },
  {
    id: "restorative-stretch",
    title: "Restorative Cuddle Stretch",
    category: "stretch",
    phase: "bliss",
    duration: 8,
    equipment: "Mat or bed, pillow",
    emoji: "🧸",
    summary: "Soothing stretches for a body that just did something huge.",
    steps: [
      { name: "Child's Pose (modified)", detail: "Knees wide, hips back toward heels only as far as comfortable. Breathe for 1 minute." },
      { name: "Neck & Shoulder Release", detail: "Seated, ear to shoulder each side, 30 sec each. Roll shoulders." },
      { name: "Ankle Circles & Toe Points", detail: "Lying down, circle ankles both directions, 10 each — helps circulation." },
      { name: "Supported Rest", detail: "Lie on your side with a pillow between knees, 2 minutes of quiet breathing." },
    ],
    safetyNote: "Avoid any deep twists or lying flat on your belly until your provider says it's fine.",
  },
  {
    id: "core-awareness",
    title: "Core Awareness Check-In",
    category: "pelvic",
    phase: "bliss",
    duration: 5,
    equipment: "None",
    emoji: "🌼",
    summary: "A gentle self-check for ab separation (diastasis recti) — no crunches!",
    steps: [
      { name: "Positioning", detail: "Lie on back, knees bent, fingers just above belly button pointing down." },
      { name: "Gentle Lift Check", detail: "Inhale, then as you exhale lift head/shoulders slightly (like a mini crunch, just to check). Feel for a gap or doming along the midline." },
      { name: "Note & Release", detail: "Note the width of any gap (finger-widths). Lie back down gently. This is info, not a workout — bring notes to your postpartum visit." },
    ],
    safetyNote: "This is a self-check only, not a strength exercise. If you feel doming/coning, avoid crunches until cleared by a pelvic floor PT.",
  },

  // ---------- Gentle Bloom (2-6 weeks) ----------
  {
    id: "pelvic-foundations",
    title: "Pelvic Floor Foundations",
    category: "pelvic",
    phase: "bloom",
    duration: 10,
    equipment: "Mat",
    emoji: "🌼",
    summary: "Kegels + gentle core activation to rebuild your foundation.",
    steps: [
      { name: "Kegel Pulses", detail: "10 quick pelvic floor pulses (lift & release), then 10 slow holds (lift, hold 5 sec, release fully)." },
      { name: "Heel Slides", detail: "Lying on back, slide one heel out straight then back, keeping low back gently pressed down. 8 each leg." },
      { name: "Transverse Ab Activation", detail: "Exhale and draw belly button gently toward spine without tilting pelvis. Hold 5 sec, 8 reps." },
      { name: "Bridge (mini)", detail: "Small pelvic tilts/mini bridges lifting hips a few inches, exhale to lift. 8 reps." },
    ],
    safetyNote: "Fully release your pelvic floor between reps — this is as important as the squeeze. Stop if you feel heaviness or leaking.",
  },
  {
    id: "seated-core",
    title: "Seated Core Reconnect",
    category: "pilates",
    phase: "bloom",
    duration: 12,
    equipment: "Chair or floor",
    emoji: "🩰",
    summary: "Gentle seated Pilates-style moves — safe, no crunching.",
    steps: [
      { name: "Seated Breathing", detail: "Tall seated posture, 360° breaths x8, feeling ribs expand." },
      { name: "Seated Marches", detail: "Lift one knee at a time while exhaling, keeping torso still. 10 each side." },
      { name: "Seated Side Reach", detail: "Reach one arm overhead and lean gently to the opposite side, exhale into the stretch. 6 each side." },
      { name: "Wall Sit (light)", detail: "Back against wall, slide down slightly (not full 90°), hold 15–20 sec, 3 rounds." },
    ],
    safetyNote: "No sit-ups, crunches, or full planks yet — keep the spine neutral throughout.",
  },
  {
    id: "walk-mobility",
    title: "Walk + Mobility Flow",
    category: "walk",
    phase: "bloom",
    duration: 15,
    equipment: "Stroller (optional)",
    emoji: "🌴",
    summary: "A slightly longer walk paired with joint mobility.",
    steps: [
      { name: "Mobility Warm-up", detail: "Ankle circles, hip circles, arm swings — 30 sec each." },
      { name: "Walk", detail: "12 minutes at a comfortable pace, arms swinging naturally." },
      { name: "Cool-down Stretch", detail: "Calf stretch + chest opener stretch, 30 sec each side." },
    ],
    safetyNote: "Wear supportive shoes; a postpartum support band can help if you feel pelvic heaviness.",
  },
  {
    id: "postnatal-flow",
    title: "Postnatal Yoga Flow",
    category: "stretch",
    phase: "bloom",
    duration: 15,
    equipment: "Mat",
    emoji: "🧘‍♀️",
    summary: "Slow, breath-led movement to release tension and rebuild body awareness.",
    steps: [
      { name: "Cat-Cow", detail: "On hands and knees, flow between arching and rounding spine with breath. 10 rounds." },
      { name: "Low Lunge Stretch", detail: "Step one foot forward into a gentle lunge, hands on knee, hold 30 sec each side." },
      { name: "Seated Forward Fold (gentle)", detail: "Legs extended, hinge slightly forward from hips, hold 30 sec." },
      { name: "Reclined Twist (gentle)", detail: "Knees to one side, shoulders flat, breathe for 30 sec each side." },
    ],
    safetyNote: "Keep twists gentle and shallow — nothing forceful through the midline yet.",
  },

  // ---------- Sunshine Strength (6-12 weeks, needs clearance) ----------
  {
    id: "low-impact-pilates",
    title: "Low-Impact Pilates Sculpt",
    category: "pilates",
    phase: "sunshine",
    duration: 20,
    equipment: "Mat, light dumbbells (optional)",
    emoji: "🩰",
    summary: "Sculpt arms, glutes & core with controlled, joint-friendly moves.",
    steps: [
      { name: "Warm-up Flow", detail: "Cat-cow + standing roll-downs, 1 minute." },
      { name: "Standing Leg Lifts", detail: "Side leg lifts holding a chair, 12 each side, 2 rounds." },
      { name: "Glute Bridges", detail: "Full bridges with a 2-sec hold at top, 15 reps, 2 rounds." },
      { name: "Bird Dog", detail: "On hands & knees, extend opposite arm/leg, keep hips square. 10 each side." },
      { name: "Standing Anti-Rotation Press", detail: "Hold a light weight or towel at chest, press out slowly without twisting torso. 10 each side." },
    ],
    safetyNote: "Skip anything that causes doming/coning at the belly button — regress to Gentle Bloom moves if that happens.",
  },
  {
    id: "beginner-strength",
    title: "Beginner Strength Circuit",
    category: "strength",
    phase: "sunshine",
    duration: 20,
    equipment: "Light dumbbells or water bottles",
    emoji: "🏋️‍♀️",
    summary: "Full-body strength basics to rebuild functional muscle.",
    steps: [
      { name: "Bodyweight Squats", detail: "12 reps, 3 rounds, focus on form over depth." },
      { name: "Wall or Knee Push-ups", detail: "10 reps, 3 rounds." },
      { name: "Dumbbell Rows", detail: "12 reps each arm, 3 rounds." },
      { name: "Standing Overhead Press", detail: "12 reps, light weight, 2 rounds." },
      { name: "Glute Bridge Marches", detail: "10 each leg, 2 rounds." },
    ],
    safetyNote: "Exhale on exertion (the hard part of the move) to protect your core and pelvic floor.",
  },
  {
    id: "kettlebell-foundations",
    title: "Kettlebell Foundations",
    category: "strength",
    phase: "sunshine",
    duration: 20,
    equipment: "Kettlebell (light-moderate)",
    emoji: "🔔",
    summary: "Controlled, no-swing kettlebell moves to build a strong foundation.",
    steps: [
      { name: "Goblet Squat", detail: "Hold kettlebell at chest, squat with control. 12 reps, 3 rounds." },
      { name: "Kettlebell Deadlift", detail: "Hinge at hips, kettlebell close to shins, stand tall squeezing glutes. 12 reps, 3 rounds." },
      { name: "Kettlebell Halo", detail: "Circle kettlebell slowly around your head, core braced. 6 each direction, 2 rounds." },
      { name: "Suitcase Carry", detail: "Carry kettlebell at your side, walk tall without leaning, 20 steps each side." },
    ],
    safetyNote: "Keep everything slow and controlled — save ballistic moves like swings for Full Bloom once you're stronger.",
  },
  {
    id: "band-pelvic-power",
    title: "Band Pelvic Power",
    category: "pelvic",
    phase: "sunshine",
    duration: 12,
    equipment: "Resistance band",
    emoji: "🌼",
    summary: "Band-resisted glute & hip work that supports pelvic floor strength.",
    steps: [
      { name: "Band Glute Bridge", detail: "Band above knees, bridge up pressing knees out against the band. 15 reps, 3 rounds." },
      { name: "Band Clamshells", detail: "Lying on side, band above knees, open knee like a clamshell. 12 each side, 2 rounds." },
      { name: "Band Standing Abduction", detail: "Band around ankles, lift leg out to the side holding onto a chair. 12 each side, 2 rounds." },
      { name: "Band Anti-Rotation Hold", detail: "Anchor band, hold handle at chest, resist it pulling you, 20 sec each side." },
    ],
    safetyNote: "Keep the pelvic floor engaged (gentle lift) through every rep — release fully between sets.",
  },
  {
    id: "standing-core",
    title: "Standing Core (No Crunches)",
    category: "pelvic",
    phase: "sunshine",
    duration: 12,
    equipment: "None",
    emoji: "🌼",
    summary: "Rebuild core strength standing up — diastasis-recti friendly.",
    steps: [
      { name: "Standing Marches with Reach", detail: "Lift knee, reach opposite arm down, exhale on lift. 12 each side." },
      { name: "Standing Woodchop (light)", detail: "Rotate torso gently pulling a light weight diagonally, controlled. 10 each side." },
      { name: "Side Bend Reach", detail: "Reach one arm overhead and bend to the side. 10 each side." },
      { name: "Wall Plank Hold", detail: "Hands on wall, walk feet back, hold a gentle plank angle 20 sec, 3 rounds." },
    ],
    safetyNote: "This replaces crunches/sit-ups, which aren't recommended until full core healing is confirmed.",
  },
  {
    id: "brisk-walk-intervals",
    title: "Brisk Walk Intervals",
    category: "walk",
    phase: "sunshine",
    duration: 20,
    equipment: "Sneakers",
    emoji: "🌴",
    summary: "Build cardio fitness with easy interval walking.",
    steps: [
      { name: "Warm-up", detail: "5 min easy pace." },
      { name: "Intervals", detail: "Alternate 2 min brisk pace / 1 min easy pace, 4 rounds." },
      { name: "Cool-down", detail: "3 min easy pace + calf & hip flexor stretch." },
    ],
    safetyNote: "Support garments can help if you feel any pelvic pressure while picking up the pace.",
  },
  {
    id: "gentle-dance-cardio",
    title: "Gentle Dance Cardio",
    category: "cardio",
    phase: "sunshine",
    duration: 15,
    equipment: "None",
    emoji: "🕺",
    summary: "Low-impact, feel-good cardio to get your heart rate up and smile on.",
    steps: [
      { name: "Warm-up Groove", detail: "Easy step-touches and arm swings to your favorite song, 2 min." },
      { name: "Low-Impact Combo", detail: "Step-touch, knee lifts, and side taps in an 8-count pattern, repeat for 8 min." },
      { name: "Cool-down Sway", detail: "Slow swaying and stretching to a calm song, 2 min." },
    ],
    safetyNote: "Keep both feet low to the ground — no jumping jacks or high-impact jumps yet.",
  },

  // ---------- Full Bloom (12+ weeks, needs clearance) ----------
  {
    id: "sculpt-tone",
    title: "Sculpt & Tone Full Body",
    category: "sculpt",
    phase: "fullbloom",
    duration: 25,
    equipment: "Dumbbells",
    emoji: "🍹",
    summary: "A full sculpt session to build strength and definition.",
    steps: [
      { name: "Goblet Squats", detail: "12 reps, 3 rounds." },
      { name: "Dumbbell Deadlifts", detail: "12 reps, 3 rounds." },
      { name: "Push-ups", detail: "10–15 reps, 3 rounds (knees ok)." },
      { name: "Renegade Rows", detail: "8 each side, 3 rounds." },
      { name: "Plank to Downward Dog", detail: "10 reps, 2 rounds." },
    ],
    safetyNote: "Full planks are great once cleared — but stop immediately if you notice doming or leaking.",
  },
  {
    id: "dance-cardio-party",
    title: "Dance Cardio Party",
    category: "cardio",
    phase: "fullbloom",
    duration: 25,
    equipment: "None",
    emoji: "🕺",
    summary: "A full dance-party sweat sesh — bring the energy!",
    steps: [
      { name: "Warm-up", detail: "3 min easy groove." },
      { name: "Cardio Combos", detail: "Grapevines, jumping jacks (if comfortable), high knees, in 4 rounds of 3 min with 30 sec rest." },
      { name: "Cool-down", detail: "3 min stretch to a slow song." },
    ],
    safetyNote: "Reintroduce jumping gradually — if you leak with jumping, swap for low-impact steps and see a pelvic floor PT.",
  },
  {
    id: "boxing-basics",
    title: "Boxing Basics (Low Impact)",
    category: "cardio",
    phase: "fullbloom",
    duration: 20,
    equipment: "None (or light weights for punches)",
    emoji: "🥊",
    summary: "Punch out the stress with beginner boxing combos.",
    steps: [
      { name: "Shadowbox Warm-up", detail: "Jab-cross combo, 2 min." },
      { name: "Combo Rounds", detail: "Jab, cross, hook combos, 4 rounds of 2 min with 30 sec rest." },
      { name: "Core Finisher", detail: "Standing punches with a twist (controlled), 1 min." },
      { name: "Cool-down", detail: "Shoulder & upper back stretch, 2 min." },
    ],
    safetyNote: "Keep footwork low-impact if you're still building back up.",
  },
  {
    id: "full-strength",
    title: "Full Body Strength",
    category: "strength",
    phase: "fullbloom",
    duration: 30,
    equipment: "Dumbbells",
    emoji: "🏋️‍♀️",
    summary: "A complete strength session for the mama ready to lift heavier.",
    steps: [
      { name: "Squats", detail: "4 sets of 10, increasing weight each set." },
      { name: "Bench/Floor Press", detail: "3 sets of 10." },
      { name: "Bent-over Rows", detail: "3 sets of 12." },
      { name: "Walking Lunges", detail: "3 sets of 10 each leg." },
      { name: "Plank", detail: "3 rounds, hold to fatigue (aim 30–45 sec)." },
    ],
    safetyNote: "Progress load slowly — about 10% more per week is a good rule of thumb.",
  },
  {
    id: "kettlebell-power-sculpt",
    title: "Kettlebell Power Sculpt",
    category: "sculpt",
    phase: "fullbloom",
    duration: 25,
    equipment: "Kettlebell",
    emoji: "🔔",
    summary: "Full-power kettlebell training now that you're cleared and strong.",
    steps: [
      { name: "Kettlebell Swings", detail: "Hip-hinge power swings, controlled breathing on the way down. 15 reps, 4 rounds." },
      { name: "Goblet Squat to Press", detail: "Squat, then press kettlebell overhead as you stand. 10 reps, 3 rounds." },
      { name: "Single-Arm Row", detail: "Hinge forward, row kettlebell to hip. 12 each side, 3 rounds." },
      { name: "Kettlebell Halo", detail: "Circle around head, core braced. 8 each direction, 2 rounds." },
      { name: "Turkish Get-Up (light, optional)", detail: "Slow, controlled floor-to-stand with kettlebell overhead. 3 each side." },
    ],
    safetyNote: "Swings are higher-impact on the core and pelvic floor — only add them once you're symptom-free with jumping and running.",
  },
  {
    id: "core-recovery-advanced",
    title: "Core Recovery — Advanced",
    category: "pelvic",
    phase: "fullbloom",
    duration: 15,
    equipment: "Mat",
    emoji: "🌼",
    summary: "Progressive core work including planks, for fully cleared cores.",
    steps: [
      { name: "Dead Bug", detail: "Slow, controlled, opposite arm/leg extension. 10 each side." },
      { name: "Forearm Plank", detail: "3 rounds, 20–40 sec holds." },
      { name: "Side Plank (modified ok)", detail: "20 sec each side, 2 rounds." },
      { name: "Pallof Press", detail: "Anti-rotation press with band or towel, 10 each side." },
    ],
    safetyNote: "If you ever notice doming, bulging, or pelvic heaviness, back off to Standing Core and check in with a pelvic floor PT.",
  },
  {
    id: "stretch-restore",
    title: "Stretch & Restore",
    category: "stretch",
    phase: "fullbloom",
    duration: 15,
    equipment: "Mat",
    emoji: "🧘‍♀️",
    summary: "A full-body stretch to wind down after a big week.",
    steps: [
      { name: "Hip Flexor Stretch", detail: "Low lunge hold, 45 sec each side." },
      { name: "Hamstring Stretch", detail: "Seated or standing forward fold, 45 sec." },
      { name: "Chest & Shoulder Opener", detail: "Clasp hands behind back, gentle lift, 30 sec." },
      { name: "Spinal Twist", detail: "Seated or lying twist, 30 sec each side." },
      { name: "Savasana", detail: "Lie flat, eyes closed, 2 minutes of stillness." },
    ],
    safetyNote: "This one's just for you — no rules here except to breathe.",
  },
];

// Weekly plan: maps day-of-week (0=Sun..6=Sat) to a category for each phase,
// so she gets one assigned workout per day instead of an open browse grid.
const WEEKLY_PLANS = {
  bliss: ["stretch", "breathe", "walk", "pelvic", "breathe", "walk", "stretch"],
  bloom: ["stretch", "pelvic", "walk", "pilates", "pelvic", "walk", "stretch"],
  sunshine: ["walk", "strength", "pelvic", "cardio", "pilates", "strength", "walk"],
  fullbloom: ["stretch", "strength", "cardio", "sculpt", "pelvic", "strength", "cardio"],
};

function getPhaseForWeek(week) {
  return PHASES.find((p) => week >= p.weeks[0] && week < p.weeks[1]) || PHASES[PHASES.length - 1];
}

function getPhaseById(id) {
  return PHASES.find((p) => p.id === id);
}
